# -*- coding: utf-8 -*-
"""Step3_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQ_pihaaX0Caq9LWJ7a32NhN-K7POq7f
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/Colab Notebooks/Project3_YOLO_model_AER850/weights/best.pt')

ardmega_pred = model.predict('/content/drive/MyDrive/Colab Notebooks/Project 3 Data/data/evaluation/ardmega.jpg', save=True, conf=0.15)

arduno_pred = model.predict('/content/drive/MyDrive/Colab Notebooks/Project 3 Data/data/evaluation/arduno.jpg', save=True, conf=0.15)

rasppi_pred = model.predict('/content/drive/MyDrive/Colab Notebooks/Project 3 Data/data/evaluation/rasppi.jpg', save=True, conf=0.15)