# -*- coding: utf-8 -*-
"""Step1_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7PJYtA7h18W9NQSam29UPcSma2o9ATe
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread('/content/drive/MyDrive/Colab Notebooks/motherboard_image.JPEG')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

_, thresholded = cv2.threshold(gray_image, 88, 255, cv2.THRESH_BINARY)
inverted_thresholded = cv2.bitwise_not(thresholded)

contours0, _ = cv2.findContours(inverted_thresholded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
filtered_contours0 = [cnt for cnt in contours0 if cv2.contourArea(cnt) > 100]
mask0 = np.zeros_like(image)
cv2.drawContours(mask0, filtered_contours0, -1, (255, 255, 255), thickness=cv2.FILLED)
masked_image0 = cv2.bitwise_and(image, mask0)

contours, _ = cv2.findContours(thresholded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
filtered_contours = [cnt for cnt in contours if cv2.contourArea(cnt) > 100]
mask = np.zeros_like(image)
cv2.drawContours(mask, filtered_contours, -1, (255, 255, 255), thickness=cv2.FILLED)
masked_image = cv2.bitwise_and(masked_image0, mask)

original_motherboard = plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.axis('off')

gray_motherboard = plt.imshow(cv2.cvtColor(gray_image, cv2.COLOR_BGR2RGB))
plt.axis('off')

thresholded_motherboard = plt.imshow(cv2.cvtColor(thresholded, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 2, 1)
contour_motherboard = plt.imshow(cv2.cvtColor(mask0, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 2, 2)
inv_contour_motherboard = plt.imshow(cv2.cvtColor(mask, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.imshow(cv2.cvtColor(masked_image, cv2.COLOR_BGR2RGB))
plt.axis('off')